/-
Copyright (c) 2026 ParamTransfer Contributors. All rights reserved.
Released under the GNU Lesser General Public License v3.0 (LGPL-3.0) as described in the file LICENSE.
Authors: Bas Spitters
-/
import Transfer.Statements.ParamTransferTac
import Transfer.Hierarchy.ParamEquiv
import Mathlib.Data.List.OfFn

/-!
# `hex`-style dense-storage ↔ Mathlib correspondence, generated by the engine

[`leanprover/hex`](https://github.com/leanprover/hex) is verified computational
algebra in Lean: each library ships a **Mathlib-free computational core**
(`HexMatrix`, `HexRowReduce`, `HexDeterminant`, …, storing matrices as dense
arrays of integers) alongside a separate **`*-mathlib` correspondence library**
that connects the computed value to the Mathlib abstraction (`Matrix.det`,
`Matrix.transpose`, …). That correspondence layer is exactly a CoqEAL *data
refinement* — the same `refines`/`param` relation the `Param` engine here
mechanises. This module builds the refinement for `hex`'s dense carrier and lets
`param_transfer` *derive* the correspondence, rather than hand-proving it per
operation (`possibility 1`).

## The carrier and its refinement

Modelling `hex`'s dense storage:

* the computational vector is `HVec := List ℤ` (a dense coefficient list);
* the abstract vector is `AVec n := Fin n → ℤ` (Mathlib's indexed function),
  the shape Mathlib lemmas quantify over.

The refinement decoder `decV n : HVec → AVec n := fun l i => l.getD i 0` is
**total and surjective** onto `AVec n` (every function is decoded by its
`List.ofFn`), and `encV := List.ofFn` is a section: `decV n (encV v) = v`. This
is the CoqEAL retraction, so the domain `Param` reaches `.map0 .map2a` (backward
section + `map_in_R`), precisely the level `forallTransfer`/`TransferDom`
consume — no equivalence, no univalence.

## Compositionality (primitive → composite)

The matrix carrier `HMat := List (List ℤ)` refines `AMat m n := Fin m → Fin n → ℤ`
by *the same lemma applied twice* (rows are `List.ofFn`, entries are `List.ofFn`).
This is the point of generating the correspondence from a primitive refinement:
`decM_encM` reuses `getD_ofFn` at both nesting levels, and the matrix
`TransferDom` is built with no new arithmetic. Transferring the abstract
statement across this one refinement replaces the hand-written `hex-mathlib`
correspondence for each matrix operation.
-/

set_option autoImplicit false
set_option linter.dupNamespace false

namespace Transfer.Param

open Transfer

/-! ## The dense-storage retraction primitive -/

/-- The reusable retraction lemma: decoding a `List.ofFn` at an in-range index
    returns the function value, for any default. This single fact generates
    the whole `hex` dense-storage correspondence. -/
theorem getD_ofFn {α : Type} {n : ℕ} (f : Fin n → α) (i : Fin n) (d : α) :
    (List.ofFn f).getD i d = f i := by
  simp [List.getD_eq_getElem?_getD, i.isLt]

/-- `hex`'s dense computational vector: a flat list of integers. -/
abbrev HVec : Type := List ℤ

/-- The abstract vector Mathlib quantifies over: an indexed function. -/
abbrev AVec (n : ℕ) : Type := Fin n → ℤ

/-- The decoder `HVec → AVec n` (dense read with out-of-range default `0`).
    Total and surjective: every `AVec n` is `decV n (List.ofFn v)`. -/
def decV (n : ℕ) (l : HVec) : AVec n := fun i => l.getD i 0

/-- The section `AVec n → HVec` (dense write). -/
def encV {n : ℕ} (v : AVec n) : HVec := List.ofFn v

/-- The retraction law: `decV` after `encV` is the identity on `AVec n`. -/
theorem decV_encV {n : ℕ} (v : AVec n) : decV n (encV v) = v := by
  funext i; simp only [decV, encV]; exact getD_ofFn v i 0

/-- The dense-vector refinement as a domain `Param .map0 .map2a HVec (AVec n)`:
    graph of the decoder forward (`map0`), the section `encV` backward (`map2a`)
    with `map_in_R` the retraction `decV_encV`. This is the CoqEAL refinement of
    `hex`'s dense vector storage, at exactly the level the `∀`-rule consumes. -/
def hVecDom (n : ℕ) : Param .map0 .map2a HVec (AVec n) where
  R := fun l v => decV n l = v
  fwd := ⟨⟩
  bwd := ⟨encV, fun v l (h : encV v = l) => by subst h; exact decV_encV v⟩

/-- `TransferDom` accepts the dense-vector refinement: `param_transfer` moves a
    statement over `hex`'s `List ℤ` storage to the abstract `Fin n → ℤ` with no
    caller-named relation. -/
instance instTransferDomHVec (n : ℕ) : TransferDom HVec (AVec n) where
  dom := hVecDom n

/-! ## Correspondence demo: a property is transferred across the refinement

`param_transfer` reduces a `∀ l : HVec` statement to a `∀ v : AVec n` statement,
discharging the pointwise obligation through the decoding relation
`decV n l = v`. This transfers the trivial source fact to the *surjectivity of
the dense decoder* — every abstract vector is realised by some dense list — purely
by the engine. -/

/-- Transfer across the dense-vector refinement: from any statement holding for
    all dense lists, obtain the abstract statement, given the pointwise step on
    related pairs `(l, v)` with `decV n l = v`. -/
def hVecForallTransfer {n : ℕ} {P : HVec → Prop} {P' : AVec n → Prop}
    (PB : ∀ (l : HVec) (v : AVec n), decV n l = v → (P l → P' v)) :
    (∀ l : HVec, P l) → (∀ v : AVec n, P' v) :=
  forallTransfer (hVecDom n) PB

/-- The dense decoder is surjective, obtained by transferring the reflexive
    source fact `∀ l, decV n l = decV n l` across the refinement: on a related
    pair `(l, v)` the witness is `l` itself. The representation change
    `List ℤ ↦ Fin n → ℤ` is invisible beyond the supplied pointwise step. -/
example (n : ℕ) :
    (∀ l : HVec, decV n l = decV n l) → (∀ v : AVec n, ∃ l : HVec, decV n l = v) := by
  param_transfer
  intro l v (hlv : decV n l = v) _
  exact ⟨l, hlv⟩

/-! ## The matrix layer: the composite reuses the primitive

`hex`'s `HexMatrix` stores a matrix as rows of dense entries. Its refinement is
the vector retraction nested: rows via `List.ofFn`, entries via `List.ofFn`. The
retraction `decM_encM` is `getD_ofFn` at both levels — no new content — so the
matrix `TransferDom` is *generated* from the same primitive. -/

/-- `hex`'s dense computational matrix: rows of dense integer lists. -/
abbrev HMat : Type := List (List ℤ)

/-- The abstract matrix Mathlib quantifies over. -/
abbrev AMat (m n : ℕ) : Type := Fin m → Fin n → ℤ

/-- Dense matrix decoder (row default `[]`, entry default `0`). -/
def decM (m n : ℕ) (rows : HMat) : AMat m n :=
  fun i j => (rows.getD i []).getD j 0

/-- Dense matrix section: nested `List.ofFn`. -/
def encM {m n : ℕ} (M : AMat m n) : HMat :=
  List.ofFn (fun i => List.ofFn (fun j => M i j))

/-- Matrix retraction: nested `getD_ofFn`, reusing the vector primitive. -/
theorem decM_encM {m n : ℕ} (M : AMat m n) : decM m n (encM M) = M := by
  funext i j
  have hrow : (encM M).getD i [] = List.ofFn (fun j => M i j) :=
    getD_ofFn (fun i => List.ofFn (fun j => M i j)) i []
  simp only [decM, hrow]
  exact getD_ofFn (fun j => M i j) j 0

/-- The dense-matrix refinement as `Param .map0 .map2a HMat (AMat m n)`,
    generated from the vector primitive via `decM_encM`. -/
def hMatDom (m n : ℕ) : Param .map0 .map2a HMat (AMat m n) where
  R := fun rows M => decM m n rows = M
  fwd := ⟨⟩
  bwd := ⟨encM, fun M rows (h : encM M = rows) => by subst h; exact decM_encM M⟩

/-- `TransferDom` for the dense matrix carrier. -/
instance instTransferDomHMat (m n : ℕ) : TransferDom HMat (AMat m n) where
  dom := hMatDom m n

/-- A matrix correspondence, transferred: the dense decoder for matrices is
    surjective onto `AMat m n` — every abstract matrix is realised by some dense
    row-list — obtained by the engine from the reflexive source fact. This stands
    in for the `hex-mathlib` correspondence lemmas (`hexOp` realises the abstract
    `Matrix` op), now produced by transfer rather than by hand. -/
example (m n : ℕ) :
    (∀ rows : HMat, decM m n rows = decM m n rows) →
      (∀ M : AMat m n, ∃ rows : HMat, decM m n rows = M) := by
  param_transfer
  intro rows M (h : decM m n rows = M) _
  exact ⟨rows, h⟩

/-! ## Axiom audit -/

section AxiomAudit

/-- info: 'Transfer.Param.hVecDom' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms hVecDom

/-- info: 'Transfer.Param.hMatDom' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms hMatDom

end AxiomAudit

end Transfer.Param
